default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>

development:
  <<: *default
  database: access_your_teaching_profile_development

test:
  <<: *default
  database: access_your_teaching_profile_test

production:
  <<: *default
  database: access_your_teaching_profile_production
  password: <%= ENV["ACCESS_YOUR_TEACHING_PROFILE_DATABASE_PASSWORD"] %>
